
[advisories]
ignore = []
version = 2

# This library uses the MPL-2 license.
#
# See https://www.mozilla.org/en-US/MPL/2.0/permissive-code-into-mpl/
[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 1.0
version = 2

[bans]
allow = []
deny = [
    # License is non-trivial
    { name = "ring" },
]
multiple-versions = "deny"
skip = []
skip-tree = [
    # Transitive dependency of two direct dependencies of passivized_htpasswd. Only used with tests.
    { name = "blowfish", version = "0.7.0" },
    # mockito 1.2 still uses hyper 0.14
    { name = "mockito", version = "1.2.0" },
    # Don't care about Redox operating system
    { name = "redox_syscall" },
    # Tokio 1.35 and simple-logger 4.3 use this old dependency
    { name = "windows-sys", version = "0.48.0" },
]
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
