name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-minimal-versions:
    name: Check build using minimal versions
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly
      - run: cargo +nightly generate-lockfile -Z minimal-versions
      - run: cargo build --all-features

  clippy:
    name: Cargo clippy
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-20.04
          - windows-2022
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: cargo clippy -- -D warnings
    timeout-minutes: 20

  deny:
    name: Cargo deny
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo install cargo-deny
      - run: cargo deny check
    timeout-minutes: 20

  test-mac:
    name: Cargo test on Mac
    strategy:
      # Only have one Mac build because Mac build setup is flaky
      matrix:
        os:
          # 13 and 14 are missing colima
          # 12 has it, but it is now unreliable, see https://github.com/abiosoft/colima/issues/1047
          - macOS-12
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: brew install docker
      #- run: colima start
      #- run: docker version
      #- run: docker info
      #- run: echo "DOCKER_HOST=$HOME/.colima/docker.sock" >> "$GITHUB_ENV"
      - run: cargo test --no-run
      #- run: cargo test --no-fail-fast
    timeout-minutes: 20

  test-nix:
    name: Cargo test on nix
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-24.04
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: docker version
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
    timeout-minutes: 30

  test-windows:
    name: Cargo test on Windows
    strategy:
      matrix:
        os:
          - windows-2022
        toolchain:
          - "1.75"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      # See https://docs.rs/crate/openssl-sys/0.9.36
      - run: vcpkg install openssl:x64-windows-static-md
      - run: vcpkg integrate install
      - run: docker version
      - run: Stop-Service docker
      - run: |
          Set-Content -Path "C:\ProgramData\Docker\config\daemon.json" -Value "{`"hosts`": [`"tcp://127.0.0.1:2375`"]}"
      - run: Start-Service docker
      - run: cargo test --no-run
      - run: |
          $env:DOCKER_HOST = 'http://localhost:2375'; cargo test --no-fail-fast
    timeout-minutes: 45
